services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-temp:/data
    networks:
      - backend

volumes:
  redis-temp:

networks:
  backend: